name: iconapp
description: Icon application

publish_to: 'none'

version: 2.0.6+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  social_share: ^2.0.5
  image_cropper: ^1.3.1
  audioplayers: ^0.16.1
  auto_route: ^0.6.9
  country_code_picker: ^1.5.0
  cached_network_image: ^2.3.2+1
  cupertino_icons: ^1.0.0
  dartz: ^0.9.1
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  easy_localization: ^2.3.3
  file_picker: ^2.0.3
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  firebase_dynamic_links: ^0.6.3
  firebase_analytics: ^6.3.0
  admob_flutter: ^1.0.1
  flushbar: ^1.10.4
  flutter_audio_recorder: ^0.5.5
  flutter_image_compress: ^0.7.0
  flutter_linkify: ^3.1.3
  flutter_local_notifications: ^3.0.2
  flutter_mobx: ^1.1.0+2
  flutter_statusbarcolor: ^0.2.3
  flutter_svg: ^0.19.0
  flutter_swiper: ^1.1.6
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  image_picker: ^0.6.7+12
  json_annotation: ^3.1.0
  logger: ^0.9.2
  lottie: ^0.6.0
  mobx: ^1.2.1+2
  modal_bottom_sheet: ^0.2.2
  path_provider: ^1.6.18
  permission_handler: ^5.0.1+1
  pin_code_fields: ^5.1.0
  pusher_websocket_flutter: ^0.2.0
  retrofit: ^1.3.4
  rxdart: ^0.24.1
  scroll_to_index: 1.0.6
  shared_preferences: ^0.5.12
  url_launcher: ^5.5.1
  vibration: ^1.5.0
  video_compress: ^2.0.0
  flick_video_player: ^0.1.1
  video_player: ^0.10.12+4
  video_thumbnail: ^0.2.2
  tutorial_coach_mark: ^0.5.1
  flutter_cache_manager: ^2.0.0
  package_info: ^0.4.3+2 
  launch_review: ^2.0.0
  visibility_detector: ^0.1.5
  flutter_staggered_grid_view: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.0
  freezed: ^0.12.1
  json_serializable: ^3.5.0
  lint: ^1.2.0
  mobx_codegen: ^1.1.0+1
  retrofit_generator: ^1.4.0+2
    



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/animations/
  fonts:
    - family: RubikBold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
    - family: RubikRegular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: RubikMedium
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
flutter_intl:
  enabled: true

