name: iconapp
description: Icon application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^1.4.4+4
  cube_transition: "^1.0.0"
  device_info: ^0.4.2+7
  cupertino_icons: ^0.1.3
  firebase_crashlytics: ^0.1.4+1
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  pusher_websocket_flutter: ^0.2.0
  shared_preferences: ^0.5.7+3
  retrofit: ^1.3.4
  dio: ^3.0.9
  logger: ^0.9.2
  rxdart: ^0.24.1
  get_it: ^4.0.2
  auto_route: ^0.6.1
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0
  json_annotation: ^3.0.1
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+1
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.18.0
  lottie: ^0.5.1
  animations: ^1.1.1
  simple_animations: ^1.3.3
  flushbar: ^1.10.4
  image_picker: ^0.6.7+2
  easy_localization: ^2.3.2
  pin_code_fields: ^3.1.2
  device_simulator: ^0.9.6
  modal_bottom_sheet: ^0.2.0+1
  vibration: ^1.4.0
  flutter_cache_manager: ^1.1.3
  # photo_view: ^0.10.0
  flutter_swiper: ^1.1.6
  video_thumbnail: ^0.2.2
  video_player: ^0.10.11+2
  audioplayers: ^0.16.0
  permission_handler: ^5.0.1+1
  flutter_audio_recorder: ^0.5.5
  url_launcher: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.11.4
  mobx_codegen: ^1.1.0+1
  auto_route_generator: ^0.6.0
  retrofit_generator: ^1.3.7+2
  json_serializable: ^3.2.5
  lint: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/animations/
  fonts:
    - family: RubikBold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
    - family: RubikRegular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: RubikMedium
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf

